[package]
name = "parse"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
edition = "2018"

[dependencies]
serde_json = "1.0.40"

[dependencies.serde]
version = "1.0.98"
features = ["derive"]
